### ISSUE TITLE
Dispatcher fragility in malformed UTF8

### ISSUE THREAD

**Issue by dginev** [dginev/CorTeX#16]
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: DbError(DbError { severity: "ERROR", code: CharacterNotInRepertoire, message: "invalid byte sequence for encoding \"UTF8\": 0x00", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: "wchar.c", line: 2017, routine: "report_invalid_encoding" })', ../src/libcore/result.rs:837
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Ventilator thread died unexpectedly!
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Context was terminated', ../src/libcore/result.rs:837
```

**Comment by dginev** [comment]
The culprit seems to be the null character again `0x00`, and it may pay off to refactor all unwrap calls around DB interactions with proper error-handling.

**Comment by dginev** [comment]
One more of these in the current new run:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: DbError(DbError { severity: "ERROR", code: CharacterNotInRepertoire, message: "invalid byte sequence for encoding \"UTF8\": 0x00", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: "wchar.c", line: 2017, routine: "report_invalid_encoding" })', /checkout/src/libcore/result.rs:860
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Ventilator thread died unexpectedly!
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Context was terminated', /checkout/src/libcore/result.rs:860
```

**Comment by dginev** [comment]
Potentially solvable as part of #18

**Comment by dginev** [comment]
I will close and can reopen if it is also encountered under Diesel
