### ISSUE TITLE
Empty work sets break dispatcher?

### ISSUE THREAD

**Issue by dginev** [dginev/CorTeX#29]
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(__Unknown, "invalid byte sequence for encoding \"UTF8\": 0x00")', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Ventilator thread died unexpectedly!
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Context was terminated', libcore/result.rs:945:5
```

Even though one can see an entire rerun complete in all experiments so far, it seems the ventilator is fragile to switching from having tasks to dispatch, to none at all. Should be an easy fix.

**Comment by dginev** [comment]
I now have a stack trace:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(__Unknown, "invalid byte sequence for encoding \"UTF8\": 0x00")', libcore/result.rs:945:5
Incoming sink job 8184 for Service: "tex_to_html", taskid: "95794"
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:206
   3: std::panicking::default_hook
             at libstd/panicking.rs:222
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:400
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:347
   6: rust_begin_unwind
             at libstd/panicking.rs:323
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   8: core::result::unwrap_failed
   9: <std::collections::hash::map::Entry<'a, K, V>>::or_insert_with
  10: cortex::manager::Server::start_ventilator
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', libcore/result.rs:945:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:206
   3: std::panicking::default_hook
             at libstd/panicking.rs:222
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:400
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:347
   6: rust_begin_unwind
             at libstd/panicking.rs:323
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   8: core::result::unwrap_failed
   9: cortex::manager::Server::start_sink
Ventilator thread died unexpectedly!
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Context was terminated', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:206
   3: std::panicking::default_hook
             at libstd/panicking.rs:222
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:400
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:347
   6: rust_begin_unwind
             at libstd/panicking.rs:323
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   8: core::result::unwrap_failed
   9: dispatcher::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:305
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:101
  13: std::rt::lang_start_internal
             at libstd/panicking.rs:284
             at libstd/panic.rs:361
             at libstd/rt.rs:58
  14: main
  15: __libc_start_main
  16: _start
```

**Comment by dginev** [comment]
The bottom line was that in certain edge cases the service name passed through ZMQ was either empty, or unknown -- and the code had an `.unwrap` assertion that expected the passed in name would always be inside the DB.

I have now hardened that method, and requests with unknown service names will be silently ignored.
